### PR TITLE
Added rviz configuration for navigation demo.

### PR DESCRIPTION
**Pull request by shokoofeh**
rviz configuration for navigation demos is added to the rviz (configs) folder and can be passed by "config" argumant to the view_robot launch file. Default is "robot.rviz".

### CODE REVIEW

**Comment by mikepurvis** [comment]
Cool, please make sure these are described on the wiki page: http://wiki.ros.org/jackal_viz

Why did model.rviz change? That one's just for visualizing the model in isolation— did it need an upgrade?

**Comment by shokoofeh** [comment]
Changes in model.rviz are camera view and enabling the TF plugin. We can discard the changes in model.rviz.

**Comment by mikepurvis** [comment]
Nah, that's fine. Just wanted to make sure it was intention and not an accident.

**Comment by mikepurvis** [comment]
Wikipage looks great, too. Thanks!

**Pull request merged**
